const products=[
{id:1,name:'Tissot PRX Powermatic 80',brand:'TISSOT',cat:'men luxury',price:18500000,img:'assets/products/tissot-prx.jpg'},
{id:2,name:'Seiko 5 Sports',brand:'SEIKO',cat:'men sport',price:24600000,img:'assets/products/seiko-5.jpg'},
{id:3,name:'ساعت کلاسیک آوان',brand:'AVAN',cat:'men luxury',price:12900000,img:'assets/products/avan-classic.jpg'},
{id:4,name:'ساعت کلاسیک زنانه آوان',brand:'AVAN',cat:'women luxury',price:15900000,img:'assets/products/avan-women.jpg'}];
const brands=['tissot','citizen','casio','seiko','rolex','omega','cartier','longines','rado','tag-heuer','certina','hamilton','orient','mido','fossil','swatch','bulova','timex','michael-kors','g-shock','movado','invicta','diesel','guess','frederique-constant','emporio-armani','tommy-hilfiger','daniel-wellington'];
const brandBox=document.getElementById('brandDropdown'); brandBox.innerHTML=brands.map(x=>`<a href="#products"><img src="assets/brands/${x}.svg" onerror="this.style.display='none'" alt="${x}"><span>${x.replaceAll('-',' ').toUpperCase()}</span></a>`).join('');
let cart=JSON.parse(localStorage.getItem('avan_cart')||'[]');
const money=n=>new Intl.NumberFormat('fa-IR').format(n)+' تومان';
function renderProducts(){let q=document.getElementById('productSearch').value.trim().toLowerCase(), f=document.querySelector('.filters .active')?.dataset.filter||'all', sort=document.getElementById('sort').value;let arr=products.filter(p=>(f==='all'||p.cat.includes(f))&&(!q||`${p.name} ${p.brand}`.toLowerCase().includes(q)));if(sort==='low')arr.sort((a,b)=>a.price-b.price);if(sort==='high')arr.sort((a,b)=>b.price-a.price);if(sort==='name')arr.sort((a,b)=>a.name.localeCompare(b.name));document.getElementById('productGrid').innerHTML=arr.map(p=>`<article class="card"><div class="card-media"><button class="wish">♡</button><img src="${p.img}" alt="${p.name}"></div><div class="card-body"><small>${p.brand}</small><h3>${p.name}</h3><p>ضمانت اصالت کالا • ارسال سریع</p><div class="price">${money(p.price)}</div><button class="add" data-add="${p.id}">افزودن به سبد 🛒</button></div></article>`).join('')||'<div class="empty">محصولی پیدا نشد.</div>';document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>add(+b.dataset.add));}
function add(id){let p=products.find(x=>x.id===id),x=cart.find(x=>x.id===id);x?x.qty++:cart.push({...p,qty:1});save();openCart();}
function save(){localStorage.setItem('avan_cart',JSON.stringify(cart));renderCart();}
function renderCart(){let count=cart.reduce((s,x)=>s+x.qty,0),total=cart.reduce((s,x)=>s+x.qty*x.price,0);document.getElementById('cartBadge').textContent=count;document.getElementById('cartPanelCount').textContent=count;document.getElementById('cartTotal').textContent=money(total);document.getElementById('cartItems').innerHTML=cart.length?cart.map(x=>`<div class="cart-row"><img src="${x.img}"><div><h4>${x.name}</h4><small>${money(x.price)}</small><div class="qty"><button data-q="${x.id}" data-d="-1">−</button><b>${x.qty}</b><button data-q="${x.id}" data-d="1">+</button></div></div><button class="remove" data-r="${x.id}">×</button></div>`).join(''):'<div class="empty">سبد خرید شما خالی است.</div>';document.querySelectorAll('[data-q]').forEach(b=>b.onclick=()=>{let x=cart.find(x=>x.id==b.dataset.q);x.qty+=+b.dataset.d;if(x.qty<1)cart=cart.filter(y=>y.id!==x.id);save()});document.querySelectorAll('[data-r]').forEach(b=>b.onclick=()=>{cart=cart.filter(x=>x.id!=b.dataset.r);save()});}
const drawer=document.getElementById('drawer'),cartPanel=document.getElementById('cartPanel'),backdrop=document.getElementById('backdrop');function closePanels(){drawer.classList.remove('open');cartPanel.classList.remove('open');backdrop.hidden=true;drawer.setAttribute('aria-hidden','true');cartPanel.setAttribute('aria-hidden','true');document.body.style.overflow=''}function openDrawer(){closePanels();drawer.classList.add('open');drawer.setAttribute('aria-hidden','false');backdrop.hidden=false;document.body.style.overflow='hidden'}function openCart(){closePanels();cartPanel.classList.add('open');cartPanel.setAttribute('aria-hidden','false');backdrop.hidden=false;document.body.style.overflow='hidden'}document.getElementById('menuBtn').onclick=openDrawer;document.getElementById('cartBtn').onclick=openCart;document.getElementById('drawerClose').onclick=closePanels;backdrop.onclick=closePanels;document.querySelectorAll('[data-close]').forEach(b=>b.onclick=closePanels);document.addEventListener('keydown',e=>e.key==='Escape'&&closePanels());drawer.querySelectorAll('a').forEach(a=>a.onclick=closePanels);document.getElementById('filters').onclick=e=>{let b=e.target.closest('button');if(!b)return;document.querySelectorAll('.filters button').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderProducts()};document.getElementById('productSearch').oninput=renderProducts;document.getElementById('sort').onchange=renderProducts;document.getElementById('searchForm').onsubmit=e=>{e.preventDefault();document.getElementById('productSearch').value=document.getElementById('searchInput').value;document.getElementById('products').scrollIntoView({behavior:'smooth'});renderProducts()};renderProducts();renderCart();
