ALTER TABLE products ADD COLUMN discount_price TEXT NOT NULL DEFAULT '';
ALTER TABLE products ADD COLUMN badge TEXT NOT NULL DEFAULT '';
ALTER TABLE products ADD COLUMN featured INTEGER NOT NULL DEFAULT 0;
ALTER TABLE products ADD COLUMN bestseller INTEGER NOT NULL DEFAULT 0;
ALTER TABLE products ADD COLUMN newest INTEGER NOT NULL DEFAULT 0;
