-- V51/V52 inventory + homepage banners
ALTER TABLE products ADD COLUMN stock_qty INTEGER NOT NULL DEFAULT 1;
ALTER TABLE products ADD COLUMN low_stock_threshold INTEGER NOT NULL DEFAULT 2;
CREATE TABLE IF NOT EXISTS homepage_banners (id INTEGER PRIMARY KEY AUTOINCREMENT,title TEXT NOT NULL DEFAULT '',subtitle TEXT NOT NULL DEFAULT '',image_url TEXT NOT NULL DEFAULT '',button_text TEXT NOT NULL DEFAULT 'مشاهده محصولات',button_link TEXT NOT NULL DEFAULT '#products',active INTEGER NOT NULL DEFAULT 1,sort_order INTEGER NOT NULL DEFAULT 0,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
