const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)], fa=n=>new Intl.NumberFormat('fa-IR').format(Number(n)||0);
const KEYS={products:'avan_admin_products_v52',orders:'avan_admin_orders_v52',customers:'avan_admin_customers_v52',categories:'avan_admin_categories_v52',brands:'avan_admin_brands_v52',coupons:'avan_admin_coupons_v52',reviews:'avan_admin_reviews_v52',settings:'avan_admin_settings_v52'};
const seedProducts=[
{id:1,name:'ساعت کلاسیک آوان',brand:'AVAN GALLERY',category:'classic',price:12900000,stock:12,sku:'AV-CL-001',image:'../assets/watch-1.jpg',desc:'مدل کلاسیک با صفحه سرمه‌ای.',specs:'موتور کوارتز، شیشه مقاوم، بند چرمی'},
{id:2,name:'Seiko 5 Sports',brand:'SEIKO',category:'sport',price:24600000,stock:7,sku:'SK-5-001',image:'../assets/watch-2.jpg',desc:'مدل اسپرت با موتور اتوماتیک.',specs:'موتور اتوماتیک، قاب استیل'},
{id:3,name:'Tissot PRX Powermatic 80',brand:'TISSOT',category:'luxury',price:18500000,stock:5,sku:'TS-PRX-001',image:'../assets/watch-3.jpg',desc:'مدل لوکس با صفحه آبی.',specs:'Powermatic 80، شیشه مقاوم'},
{id:4,name:'ساعت کلاسیک زنانه آوان',brand:'AVAN GALLERY',category:'women',price:15900000,stock:9,sku:'AV-W-001',image:'../assets/watch-1.jpg',desc:'مدل ظریف مینیمال.',specs:'صفحه مینیمال، بند فلزی'}];
const read=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}}, write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
let products=read(KEYS.products,seedProducts), orders=read(KEYS.orders,[{id:'#1048',customer:'علی رضایی',product:'Tissot PRX',amount:18500000,payment:'موفق',status:'در حال ارسال',tracking:'TRK-1048'},{id:'#1047',customer:'محمد کریمی',product:'Seiko 5 Sports',amount:24600000,payment:'موفق',status:'در انتظار',tracking:''},{id:'#1046',customer:'سارا احمدی',product:'ساعت زنانه آوان',amount:15900000,payment:'در انتظار',status:'ثبت نشده',tracking:''}]);
let customers=read(KEYS.customers,[{name:'علی رضایی',phone:'0912***',orders:4,total:73500000,status:'فعال'},{name:'محمد کریمی',phone:'0935***',orders:2,total:43200000,status:'فعال'},{name:'سارا احمدی',phone:'0911***',orders:1,total:15900000,status:'فعال'}]);
let categories=read(KEYS.categories,['کلاسیک','لوکس','اسپرت','مردانه','زنانه']), brands=read(KEYS.brands,['TISSOT','SEIKO','CASIO','ROLEX','OMEGA','CARTIER','LONGINES','RADO','HAMILTON','CERTINA','MIDO','ORIENT','SWATCH','FOSSIL','TIMEX','BULOVA','G-SHOCK','MICHAEL KORS','AVAN GALLERY']);
let coupons=read(KEYS.coupons,[{code:'WELCOME10',percent:10,status:'فعال'},{code:'VIP20',percent:20,status:'فعال'}]), reviews=read(KEYS.reviews,[{name:'مریم',product:'ساعت کلاسیک آوان',rating:5,status:'در انتظار'},{name:'رضا',product:'Seiko 5 Sports',rating:4,status:'تأیید شده'}]);
let settings=read(KEYS.settings,{shopName:'آوان گالری',phone:'0991-848-3441',address:'مازندران',freeShipping:6000000}); let current='dashboard';
function saveAll(){write(KEYS.products,products);write(KEYS.orders,orders);write(KEYS.customers,customers);write(KEYS.categories,categories);write(KEYS.brands,brands);write(KEYS.coupons,coupons);write(KEYS.reviews,reviews);write(KEYS.settings,settings);$('#navProductsCount').textContent=fa(products.length)}
function head(title,sub,action=''){return `<div class="page-head"><div><h2>${title}</h2><p>${sub}</p></div>${action}</div>`}
function dashboard(){const revenue=orders.filter(o=>o.payment==='موفق').reduce((s,o)=>s+o.amount,0);return head('داشبورد','نمای کلی فروشگاه، فروش و عملیات')+`<div class="cards"><div class="stat"><span class="icon">◈</span><small>محصولات</small><strong>${fa(products.length)}</strong></div><div class="stat"><span class="icon">▣</span><small>سفارش‌ها</small><strong>${fa(orders.length)}</strong></div><div class="stat"><span class="icon">♙</span><small>مشتریان</small><strong>${fa(customers.length)}</strong></div><div class="stat"><span class="icon">◉</span><small>فروش ثبت‌شده</small><strong>${fa(revenue)} تومان</strong></div></div><div class="grid2"><section class="panel"><h3>عملیات سریع</h3><div class="toolbar"><button class="gold" data-go="products">＋ افزودن محصول</button><button class="ghost" data-go="orders">مدیریت سفارش‌ها</button><button class="ghost" data-go="coupons">کد تخفیف</button></div></section><section class="panel"><h3>هشدارها</h3><div class="list-cards"><div class="info-card"><h4>موجودی کم</h4><p>${fa(products.filter(p=>p.stock<3).length)} محصول زیر حداقل موجودی است.</p></div><div class="info-card"><h4>سفارش در انتظار</h4><p>${fa(orders.filter(o=>o.status.includes('انتظار')).length)} سفارش نیاز به بررسی دارد.</p></div></div></section></div>`}
function productsPage(){return head('مدیریت محصولات','افزودن، ویرایش، حذف، قیمت، موجودی و مشخصات',`<button class="gold" id="newProduct">＋ افزودن محصول</button>`)+`<div class="toolbar"><input id="adminSearch" placeholder="جستجوی نام، برند یا SKU..."/><select id="adminCategory"><option value="all">همه دسته‌ها</option>${categories.map(c=>`<option value="${c}">${c}</option>`).join('')}</select><button class="ghost" id="exportProducts">خروجی JSON</button></div><div class="panel"><div class="products-admin" id="adminProducts"></div></div>`}
function renderProducts(q='',cat='all'){const box=$('#adminProducts');if(!box)return;const arr=products.filter(p=>(cat==='all'||p.category===cat)&&(!q||(`${p.name} ${p.brand} ${p.sku}`).toLowerCase().includes(q.toLowerCase())));box.innerHTML=arr.map(p=>`<article class="admin-product"><img src="${p.image}" alt=""><div><h4>${p.name}</h4><p>${p.brand} • SKU: ${p.sku||'-'} • ${fa(p.price)} تومان</p><p>${p.desc||''}</p></div><div class="stock"><span class="pill ${p.stock<3?'pending':''}">${fa(p.stock)} موجود</span></div><div class="actions"><button class="small-btn" data-edit="${p.id}">ویرایش</button><button class="small-btn danger" data-delete="${p.id}">حذف</button></div></article>`).join('')||'<div class="notice">محصولی پیدا نشد.</div>'}
function ordersPage(){return head('مدیریت سفارش‌ها','پرداخت، وضعیت ارسال و کد رهگیری')+`<div class="panel"><div class="table-wrap"><table class="table"><tr><th>شماره</th><th>مشتری</th><th>محصول</th><th>مبلغ</th><th>پرداخت</th><th>وضعیت</th><th>رهگیری</th><th>عملیات</th></tr>${orders.map(o=>`<tr><td>${o.id}</td><td>${o.customer}</td><td>${o.product}</td><td>${fa(o.amount)}</td><td><select class="inline-select" data-pay="${o.id}"><option ${o.payment==='موفق'?'selected':''}>موفق</option><option ${o.payment==='در انتظار'?'selected':''}>در انتظار</option><option>لغو</option></select></td><td><select class="inline-select" data-status="${o.id}"><option ${o.status==='در انتظار'?'selected':''}>در انتظار</option><option ${o.status==='تأیید شده'?'selected':''}>تأیید شده</option><option ${o.status==='در حال ارسال'?'selected':''}>در حال ارسال</option><option ${o.status==='تحویل شده'?'selected':''}>تحویل شده</option><option ${o.status==='لغو شده'?'selected':''}>لغو شده</option></select></td><td><input class="inline-input" data-track="${o.id}" value="${o.tracking||''}" placeholder="کد رهگیری"></td><td><button class="small-btn" data-save-order="${o.id}">ذخیره</button></td></tr>`).join('')}</table></div></div>`}
function tablePage(title,sub,headers,rows){return head(title,sub)+`<div class="panel"><div class="table-wrap"><table class="table"><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr>${rows.map(r=>`<tr>${r.map(c=>`<td>${c}</td>`).join('')}</tr>`).join('')}</table></div></div>`}
function generic(title,sub,arr,addLabel){return head(title,sub,addLabel?`<button class="gold" data-add-simple="${title}">＋ ${addLabel}</button>`:'')+`<div class="list-cards">${arr.map((x,i)=>`<div class="info-card"><h4>${x}</h4><p>فعال و قابل مدیریت از پنل</p><div class="actions"><button class="small-btn" data-simple-edit="${i}">ویرایش</button><button class="small-btn danger" data-simple-delete="${i}">حذف</button></div></div>`).join('')}</div>`}
function render(){const c=$('#adminContent');let html='';switch(current){case'dashboard':html=dashboard();break;case'products':html=productsPage();break;case'orders':html=ordersPage();break;case'customers':html=tablePage('مشتریان','حساب، سابقه خرید و وضعیت مشتریان',['نام','موبایل','تعداد سفارش','مجموع خرید','وضعیت'],customers.map(x=>[x.name,x.phone,fa(x.orders),fa(x.total)+' تومان',`<span class="pill">${x.status}</span>`]));break;case'categories':html=generic('دسته‌بندی‌ها','ساختار محصولات',categories,'دسته‌بندی');break;case'brands':html=generic('برندها','کاتالوگ برندهای فروشگاه',brands,'برند');break;case'coupons':html=tablePage('کدهای تخفیف','ساخت، فعال/غیرفعال و مدیریت کمپین',['کد','درصد','وضعیت'],coupons.map((x,i)=>[x.code,fa(x.percent)+'٪',`<button class="small-btn" data-toggle-coupon="${i}">${x.status}</button>`]));break;case'reviews':html=tablePage('نظرات مشتریان','تأیید یا رد دیدگاه‌ها',['مشتری','محصول','امتیاز','وضعیت','عملیات'],reviews.map((x,i)=>[x.name,x.product,'★'.repeat(x.rating),x.status,`<button class="small-btn" data-review="${i}">تغییر وضعیت</button>`]));break;case'content':html=generic('محتوا و بنرها','مدیریت Hero، مجله، صفحات ثابت و بنرها',['Hero اصلی','بنر فروشگاه','مجله آوان','درباره ما','تماس با ما','قوانین و حریم خصوصی'],'محتوا');break;case'settings':html=head('تنظیمات فروشگاه','اطلاعات پایه، ارسال و عملیات')+`<div class="panel"><div class="form-grid"><label>نام فروشگاه<input id="sName" value="${settings.shopName}"></label><label>شماره تماس<input id="sPhone" value="${settings.phone}"></label><label class="full">آدرس<input id="sAddress" value="${settings.address}"></label><label>حداقل مبلغ ارسال رایگان<input id="sShip" type="number" value="${settings.freeShipping}"></label></div><div class="modal-actions"><button class="gold" id="saveSettings">ذخیره تنظیمات</button></div></div>`;break}c.innerHTML=html;$('#pageTitle').textContent=document.querySelector(`#adminNav button[data-page="${current}"] span`)?.textContent||'داشبورد';bindPage()}
function bindPage(){
  if(current==='dashboard'){
    $$('[data-go]').forEach(b=>b.onclick=()=>{current=b.dataset.go;$$('#adminNav button').forEach(x=>x.classList.toggle('active',x.dataset.page===current));render()});
  }
  if(current==='products'){
    renderProducts();
    $('#newProduct').onclick=()=>openProduct();
    $('#adminSearch').oninput=e=>renderProducts(e.target.value,$('#adminCategory').value);
    $('#adminCategory').onchange=e=>renderProducts($('#adminSearch').value,e.target.value);
    $('#exportProducts').onclick=()=>download('avan-products.json',JSON.stringify(products,null,2));
  }
  if(current==='orders'){
    $$('[data-save-order]').forEach(b=>b.onclick=()=>{const o=orders.find(x=>x.id===b.dataset.saveOrder);if(!o)return;o.payment=$(`[data-pay="${o.id}"]`).value;o.status=$(`[data-status="${o.id}"]`).value;o.tracking=$(`[data-track="${o.id}"]`).value;saveAll();render()});
  }
  if(current==='coupons'){
    $$('[data-toggle-coupon]').forEach(b=>b.onclick=()=>{coupons[+b.dataset.toggleCoupon].status=coupons[+b.dataset.toggleCoupon].status==='فعال'?'غیرفعال':'فعال';saveAll();render()});
  }
  if(current==='reviews'){
    $$('[data-review]').forEach(b=>b.onclick=()=>{reviews[+b.dataset.review].status=reviews[+b.dataset.review].status==='تأیید شده'?'در انتظار':'تأیید شده';saveAll();render()});
  }
  if(current==='settings'){
    $('#saveSettings').onclick=()=>{settings={shopName:$('#sName').value,phone:$('#sPhone').value,address:$('#sAddress').value,freeShipping:Number($('#sShip').value)||0};saveAll();alert('تنظیمات ذخیره شد')};
  }
  $$('[data-add-simple]').forEach(b=>b.onclick=()=>{const v=prompt(`نام ${b.dataset.addSimple} را وارد کنید:`);if(!v)return;if(current==='categories')categories.push(v);if(current==='brands')brands.push(v);saveAll();render()});
  $$('[data-simple-delete]').forEach(b=>b.onclick=()=>{const i=+b.dataset.simpleDelete;if(current==='categories')categories.splice(i,1);if(current==='brands')brands.splice(i,1);saveAll();render()});
  $$('[data-simple-edit]').forEach(b=>b.onclick=()=>{const i=+b.dataset.simpleEdit,arr=current==='categories'?categories:brands;const v=prompt('نام جدید:',arr[i]);if(v){arr[i]=v;saveAll();render()}});
}
function download(name,data){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type:'application/json'}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
function openProduct(id){const p=products.find(x=>x.id==id);$('#modalTitle').textContent=p?'ویرایش محصول':'افزودن محصول';$('#productId').value=p?.id||'';$('#pName').value=p?.name||'';$('#pBrand').value=p?.brand||'';$('#pCategory').value=p?.category||'classic';$('#pPrice').value=p?.price||'';$('#pStock').value=p?.stock??'';$('#pSku').value=p?.sku||'';$('#pImage').value=p?.image||'../assets/watch-1.jpg';$('#pDesc').value=p?.desc||'';$('#pSpecs').value=p?.specs||'';$('#pImageFile').value='';$('#productModal').classList.add('open');$('#productModal').setAttribute('aria-hidden','false')}
function closeModal(){$('#productModal').classList.remove('open');$('#productModal').setAttribute('aria-hidden','true')}
$('#adminNav').addEventListener('click',e=>{const b=e.target.closest('button[data-page]');if(!b)return;current=b.dataset.page;$$('#adminNav button').forEach(x=>x.classList.toggle('active',x===b));render();$('#adminSidebar').classList.remove('open')});
$('#productForm').addEventListener('submit',async e=>{e.preventDefault();const id=$('#productId').value;let image=$('#pImage').value||'../assets/watch-1.jpg';const file=$('#pImageFile').files[0];if(file){image=await new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(file)})}const p={id:id?Number(id):Date.now(),name:$('#pName').value.trim(),brand:$('#pBrand').value.trim(),category:$('#pCategory').value,price:Number($('#pPrice').value)||0,stock:Number($('#pStock').value)||0,sku:$('#pSku').value.trim(),image,desc:$('#pDesc').value.trim(),specs:$('#pSpecs').value.trim()};products=id?products.map(x=>x.id===Number(id)?p:x):[p,...products];saveAll();closeModal();render()});
$('#adminContent').addEventListener('click',e=>{const ed=e.target.closest('[data-edit]'),del=e.target.closest('[data-delete]');if(ed)openProduct(ed.dataset.edit);if(del&&confirm('این محصول حذف شود؟')){products=products.filter(x=>x.id!==Number(del.dataset.delete));saveAll();render()}});
$('#modalClose').onclick=closeModal;$('#cancelProduct').onclick=closeModal;$('#productModal').addEventListener('click',e=>{if(e.target.id==='productModal')closeModal()});$('#adminMenu').onclick=()=>$('#adminSidebar').classList.toggle('open');$('#adminLogout').onclick=()=>location.href='../index.html';saveAll();render();
