const json=(x,status=200,headers={})=>new Response(JSON.stringify(x),{status,headers:{'content-type':'application/json;charset=utf-8','cache-control':'no-store',...headers}});
const read=async r=>{try{return await r.json()}catch{return{}}};
const hash=async p=>{const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode('avan:'+p));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')};
const token=()=>{const a=new Uint8Array(32);crypto.getRandomValues(a);return [...a].map(x=>x.toString(16).padStart(2,'0')).join('')};
const cookie=(r,n)=>{const v=(r.headers.get('Cookie')||'').split(';').map(x=>x.trim()).find(x=>x.startsWith(n+'='));return v?decodeURIComponent(v.split('=').slice(1).join('=')):null};
const setCookie=t=>`avan_session=${encodeURIComponent(t)}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=604800`;
async function me(req,e){const t=cookie(req,'avan_session');if(!t)return null;return e.DB.prepare("SELECT u.id,u.name,u.phone,u.email,u.role FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.id=? AND s.expires_at>datetime('now')").bind(t).first()}
const auth=(u,role)=>u&&(role?u.role===role:true);
async function productList(e,u){let sql=`SELECT p.*,c.name category_name,c.slug category_slug,COALESCE(AVG(r.rating),0) rating,COUNT(r.id) review_count FROM products p LEFT JOIN categories c ON c.id=p.category_id LEFT JOIN reviews r ON r.product_id=p.id AND r.status='approved' WHERE p.active=1`,a=[];let q=u.searchParams.get('q'),brand=u.searchParams.get('brand'),cat=u.searchParams.get('category'),min=u.searchParams.get('min'),max=u.searchParams.get('max'),sort=u.searchParams.get('sort');if(q){sql+=' AND (p.name LIKE ? OR p.brand LIKE ? OR p.sku LIKE ?)';a.push('%'+q+'%','%'+q+'%','%'+q+'%')}if(brand){sql+=' AND p.brand=?';a.push(brand)}if(cat){sql+=' AND c.slug=?';a.push(cat)}if(min){sql+=' AND p.price>=?';a.push(+min)}if(max){sql+=' AND p.price<=?';a.push(+max)}sql+=' GROUP BY p.id ORDER BY '+(sort==='price_asc'?'p.price ASC':sort==='price_desc'?'p.price DESC':'p.featured DESC,p.id DESC')+' LIMIT 120';const {results=[]}=await e.DB.prepare(sql).bind(...a).all();return results.map(p=>({...p,gallery:JSON.parse(p.gallery||'[]'),specs:JSON.parse(p.specs||'{}')}))}
async function admin(req,e,u){if(!auth(u,'admin'))return json({error:'دسترسی مدیر لازم است'},403);const path=new URL(req.url).pathname;
if(req.method==='GET'&&path==='/api/admin/dashboard'){const [p,o,c,r,pend]=await Promise.all([e.DB.prepare('SELECT COUNT(*) n FROM products').first(),e.DB.prepare('SELECT COUNT(*) n FROM orders').first(),e.DB.prepare("SELECT COUNT(*) n FROM users WHERE role='customer'").first(),e.DB.prepare("SELECT COALESCE(SUM(total-discount),0) n FROM orders WHERE payment_status='paid'").first(),e.DB.prepare("SELECT COUNT(*) n FROM orders WHERE status='pending'").first()]);return json({products:p.n,orders:o.n,customers:c.n,revenue:r.n,pending:pend.n})}
if(req.method==='GET'&&path==='/api/admin/products'){const {results=[]}=await e.DB.prepare('SELECT * FROM products ORDER BY id DESC').all();return json(results.map(x=>({...x,gallery:JSON.parse(x.gallery||'[]'),specs:JSON.parse(x.specs||'{}')})))}
if(req.method==='POST'&&path==='/api/admin/products'){const b=await read(req);if(!b.name||!b.brand)return json({error:'نام و برند الزامی است'},400);let slug=(b.slug||`${b.brand}-${b.name}-${Date.now()}`).replace(/[^a-zA-Z0-9\u0600-\u06ff]+/g,'-');await e.DB.prepare(`INSERT INTO products(category_id,brand,name,slug,description,price,compare_price,stock,sku,image,gallery,specs,featured,active) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(b.categoryId||null,b.brand,b.name,slug,b.description||'',+b.price||0,b.comparePrice||null,+b.stock||0,b.sku||'',b.image||'',JSON.stringify(b.gallery||[]),JSON.stringify(b.specs||{}),b.featured?1:0,b.active===0?0:1).run();return json({ok:true})}
if(req.method==='PATCH'&&path.startsWith('/api/admin/products/')){const id=path.split('/').pop(),b=await read(req),map={categoryId:'category_id',brand:'brand',name:'name',description:'description',price:'price',comparePrice:'compare_price',stock:'stock',sku:'sku',image:'image',featured:'featured',active:'active'};let f=[],a=[];for(const[k,c]of Object.entries(map))if(b[k]!==undefined){f.push(c+'=?');a.push(['featured','active'].includes(k)?(b[k]?1:0):b[k])}if(b.gallery!==undefined){f.push('gallery=?');a.push(JSON.stringify(b.gallery))}if(b.specs!==undefined){f.push('specs=?');a.push(JSON.stringify(b.specs))}if(!f.length)return json({error:'تغییری ارسال نشده'},400);f.push('updated_at=CURRENT_TIMESTAMP');a.push(id);await e.DB.prepare('UPDATE products SET '+f.join(',')+' WHERE id=?').bind(...a).run();return json({ok:true})}
if(req.method==='DELETE'&&path.startsWith('/api/admin/products/')){await e.DB.prepare('DELETE FROM products WHERE id=?').bind(path.split('/').pop()).run();return json({ok:true})}
if(req.method==='GET'&&path==='/api/admin/orders'){const {results=[]}=await e.DB.prepare('SELECT o.*,u.name customer_name,u.phone customer_phone FROM orders o LEFT JOIN users u ON u.id=o.user_id ORDER BY o.id DESC LIMIT 500').all();return json(results)}
if(req.method==='PATCH'&&path.startsWith('/api/admin/orders/')){const id=path.split('/').pop(),b=await read(req),f=[],a=[];for(const k of ['status','payment_status','tracking_code','shipping_method'])if(b[k]!==undefined){f.push(k+'=?');a.push(b[k])}if(b.status==='shipped'){f.push("shipped_at=datetime('now')")}if(!f.length)return json({error:'تغییری ارسال نشده'},400);a.push(id);await e.DB.prepare('UPDATE orders SET '+f.join(',')+',updated_at=CURRENT_TIMESTAMP WHERE id=?').bind(...a).run();const o=await e.DB.prepare('SELECT user_id,order_number,status FROM orders WHERE id=?').bind(id).first();if(o?.user_id)await e.DB.prepare('INSERT INTO notifications(user_id,title,body,type) VALUES(?,?,?,?)').bind(o.user_id,'به‌روزرسانی سفارش','وضعیت سفارش '+o.order_number+' تغییر کرد.','order').run();return json({ok:true})}
if(req.method==='GET'&&path==='/api/admin/customers'){const {results=[]}=await e.DB.prepare("SELECT id,name,phone,email,role,created_at FROM users ORDER BY id DESC").all();return json(results)}
if(req.method==='GET'&&path==='/api/admin/categories'){const {results=[]}=await e.DB.prepare('SELECT * FROM categories ORDER BY sort_order,id').all();return json(results)}
if(req.method==='POST'&&path==='/api/admin/categories'){const b=await read(req);await e.DB.prepare('INSERT INTO categories(name,slug,image,sort_order) VALUES(?,?,?,?)').bind(b.name,b.slug,b.image||'',+b.sortOrder||0).run();return json({ok:true})}
if(req.method==='GET'&&path==='/api/admin/reviews'){const {results=[]}=await e.DB.prepare("SELECT r.*,u.name user_name,p.name product_name FROM reviews r JOIN users u ON u.id=r.user_id JOIN products p ON p.id=r.product_id ORDER BY r.id DESC").all();return json(results)}
if(req.method==='PATCH'&&path.startsWith('/api/admin/reviews/')){const id=path.split('/').pop(),b=await read(req);await e.DB.prepare('UPDATE reviews SET status=? WHERE id=?').bind(b.status,id).run();return json({ok:true})}
if(req.method==='GET'&&path==='/api/admin/coupons'){const {results=[]}=await e.DB.prepare('SELECT * FROM coupons ORDER BY id DESC').all();return json(results)}
if(req.method==='POST'&&path==='/api/admin/coupons'){const b=await read(req);await e.DB.prepare('INSERT INTO coupons(code,type,value,min_order,max_uses,expires_at) VALUES(?,?,?,?,?,?)').bind(String(b.code).toUpperCase(),b.type||'percent',+b.value||0,+b.minOrder||0,b.maxUses||null,b.expiresAt||null).run();return json({ok:true})}
if(req.method==='GET'&&path==='/api/admin/banners'){const {results=[]}=await e.DB.prepare('SELECT * FROM banners ORDER BY sort_order,id').all();return json(results)}
if(req.method==='POST'&&path==='/api/admin/banners'){const b=await read(req);await e.DB.prepare('INSERT INTO banners(title,subtitle,image,link,sort_order) VALUES(?,?,?,?,?)').bind(b.title,b.subtitle||'',b.image||'',b.link||'',+b.sortOrder||0).run();return json({ok:true})}
if(req.method==='GET'&&path==='/api/admin/settings'){const {results=[]}=await e.DB.prepare('SELECT * FROM site_settings ORDER BY key').all();return json(Object.fromEntries(results.map(x=>[x.key,x.value])))}
if(req.method==='POST'&&path==='/api/admin/settings'){const b=await read(req);for(const[k,v]of Object.entries(b))await e.DB.prepare('INSERT INTO site_settings(key,value) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value').bind(k,String(v)).run();return json({ok:true})}
return json({error:'Admin API not found'},404)}
export default {async fetch(req,e){const u=new URL(req.url);try{if(u.pathname.startsWith('/api/')){const b=await read(req);if(u.pathname==='/api/auth/register'&&req.method==='POST'){if(!b.name||!b.phone||!b.password||b.password.length<6)return json({error:'اطلاعات ثبت‌نام ناقص است'},400);if(await e.DB.prepare('SELECT id FROM users WHERE phone=?').bind(b.phone).first())return json({error:'این شماره قبلاً ثبت شده'},409);const r=await e.DB.prepare('INSERT INTO users(name,phone,email,password_hash) VALUES(?,?,?,?)').bind(b.name,b.phone,b.email||'',await hash(b.password)).run();const t=token();await e.DB.prepare("INSERT INTO sessions(id,user_id,expires_at) VALUES(?,?,datetime('now','+7 days'))").bind(t,r.meta.last_row_id).run();return json({ok:true,user:{id:r.meta.last_row_id,name:b.name,phone:b.phone,role:'customer'}},200,{'set-cookie':setCookie(t)})}
if(u.pathname==='/api/auth/login'&&req.method==='POST'){const x=await e.DB.prepare('SELECT id,name,phone,email,role FROM users WHERE phone=? AND password_hash=?').bind(b.phone,await hash(b.password||'')).first();if(!x)return json({error:'شماره یا رمز اشتباه است'},401);const t=token();await e.DB.prepare("INSERT INTO sessions(id,user_id,expires_at) VALUES(?,?,datetime('now','+7 days'))").bind(t,x.id).run();return json({ok:true,user:x},200,{'set-cookie':setCookie(t)})}
if(u.pathname==='/api/auth/logout'){const t=cookie(req,'avan_session');if(t)await e.DB.prepare('DELETE FROM sessions WHERE id=?').bind(t).run();return json({ok:true},200,{'set-cookie':'avan_session=; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=0'})}
if(u.pathname==='/api/auth/me')return json({user:await me(req,e)});
if(u.pathname==='/api/products')return json(await productList(e,u));
if(u.pathname.startsWith('/api/products/')){const id=u.pathname.split('/').pop();const p=await e.DB.prepare('SELECT p.*,c.name category_name,c.slug category_slug,COALESCE(AVG(r.rating),0) rating,COUNT(r.id) review_count FROM products p LEFT JOIN categories c ON c.id=p.category_id LEFT JOIN reviews r ON r.product_id=p.id AND r.status="approved" WHERE p.id=? GROUP BY p.id').bind(id).first();if(!p)return json({error:'محصول پیدا نشد'},404);p.gallery=JSON.parse(p.gallery||'[]');p.specs=JSON.parse(p.specs||'{}');const {results:reviews=[]}=await e.DB.prepare("SELECT r.rating,r.title,r.body,r.created_at,u.name FROM reviews r JOIN users u ON u.id=r.user_id WHERE r.product_id=? AND r.status='approved' ORDER BY r.id DESC").bind(id).all();p.reviews=reviews;return json(p)}
if(u.pathname==='/api/categories'){const {results=[]}=await e.DB.prepare('SELECT * FROM categories WHERE active=1 ORDER BY sort_order,id').all();return json(results)}
const user=await me(req,e);if(u.pathname.startsWith('/api/admin/'))return admin(req,e,user);
if(u.pathname==='/api/cart'){if(!user)return json({error:'ورود لازم است'},401);if(req.method==='GET'){const c=await e.DB.prepare('SELECT items FROM carts WHERE user_id=?').bind(user.id).first();return json({items:c?JSON.parse(c.items):[]})}await e.DB.prepare("INSERT INTO carts(user_id,items) VALUES(?,?) ON CONFLICT(user_id) DO UPDATE SET items=excluded.items,updated_at=CURRENT_TIMESTAMP").bind(user.id,JSON.stringify(b.items||[])).run();return json({ok:true})}
if(u.pathname==='/api/favorites'){if(!user)return json({error:'ورود لازم است'},401);if(req.method==='GET'){const {results=[]}=await e.DB.prepare('SELECT p.* FROM favorites f JOIN products p ON p.id=f.product_id WHERE f.user_id=?').bind(user.id).all();return json(results)}const id=b.productId;if(req.method==='POST')await e.DB.prepare('INSERT OR IGNORE INTO favorites(user_id,product_id) VALUES(?,?)').bind(user.id,id).run();else if(req.method==='DELETE')await e.DB.prepare('DELETE FROM favorites WHERE user_id=? AND product_id=?').bind(user.id,id).run();return json({ok:true})}
if(u.pathname==='/api/reviews'&&req.method==='POST'){if(!user)return json({error:'ورود لازم است'},401);if(!b.productId||!b.rating)return json({error:'امتیاز الزامی است'},400);await e.DB.prepare('INSERT INTO reviews(user_id,product_id,rating,title,body) VALUES(?,?,?,?,?)').bind(user.id,b.productId,+b.rating,b.title||'',b.body||'').run();return json({ok:true,message:'نظر شما پس از بررسی منتشر می‌شود'})}
if(u.pathname==='/api/orders'&&req.method==='GET'){if(!user)return json({error:'ورود لازم است'},401);const {results=[]}=await e.DB.prepare('SELECT * FROM orders WHERE user_id=? ORDER BY id DESC').bind(user.id).all();return json(results)}
if(u.pathname==='/api/orders'&&req.method==='POST'){if(!user)return json({error:'ورود لازم است'},401);if(!b.items?.length)return json({error:'سبد خرید خالی است'},400);let total=0,verified=[];for(const x of b.items){const p=await e.DB.prepare('SELECT id,name,brand,price,stock,image FROM products WHERE id=? AND active=1').bind(x.productId).first();const qty=Math.max(1,Math.min(99,+x.qty||1));if(!p||p.stock<qty)return json({error:'محصول یا موجودی کافی نیست'},400);total+=p.price*qty;verified.push({...p,qty})}let discount=0;if(b.coupon){const c=await e.DB.prepare("SELECT * FROM coupons WHERE code=? AND active=1 AND (expires_at IS NULL OR expires_at>datetime('now')) AND (max_uses IS NULL OR used_count<max_uses)").bind(String(b.coupon).toUpperCase()).first();if(c&&total>=c.min_order){discount=c.type==='percent'?Math.floor(total*c.value/100):Math.min(total,c.value)}}const num='AVN-'+Date.now().toString(36).toUpperCase();const r=await e.DB.prepare('INSERT INTO orders(user_id,order_number,total,discount,coupon_code,receiver,phone,province,city,address,postal_code,note) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)').bind(user.id,num,total,discount,b.coupon||'',b.receiver,b.phone,b.province,b.city,b.address,b.postalCode||'',b.note||'').run();for(const p of verified){await e.DB.prepare('INSERT INTO order_items(order_id,product_id,product_name,brand,price,qty,image) VALUES(?,?,?,?,?,?,?)').bind(r.meta.last_row_id,p.id,p.name,p.brand,p.price,p.qty,p.image).run();await e.DB.prepare('UPDATE products SET stock=stock-? WHERE id=?').bind(p.qty,p.id).run()}if(b.coupon)await e.DB.prepare('UPDATE coupons SET used_count=used_count+1 WHERE code=?').bind(String(b.coupon).toUpperCase()).run();await e.DB.prepare("INSERT INTO carts(user_id,items) VALUES(?,?) ON CONFLICT(user_id) DO UPDATE SET items='[]',updated_at=CURRENT_TIMESTAMP").bind(user.id).run();await e.DB.prepare('INSERT INTO notifications(user_id,title,body,type) VALUES(?,?,?,?)').bind(user.id,'سفارش ثبت شد','سفارش '+num+' با موفقیت ثبت شد.','order').run();return json({ok:true,orderNumber:num,total,discount,payable:total-discount})}
if(u.pathname==='/api/profile'){if(!user)return json({error:'ورود لازم است'},401);if(req.method==='GET')return json({user});await e.DB.prepare('UPDATE users SET name=?,email=? WHERE id=?').bind(b.name||user.name,b.email||'',user.id).run();return json({ok:true})}
if(u.pathname==='/api/notifications'){if(!user)return json({error:'ورود لازم است'},401);if(req.method==='GET'){const {results=[]}=await e.DB.prepare('SELECT * FROM notifications WHERE user_id=? ORDER BY id DESC LIMIT 30').bind(user.id).all();return json(results)}await e.DB.prepare("UPDATE notifications SET read_at=datetime('now') WHERE user_id=? AND read_at IS NULL").bind(user.id).run();return json({ok:true})}
if(u.pathname==='/api/site'){const {results=[]}=await e.DB.prepare('SELECT * FROM site_settings').all();const {results:banners=[]}=await e.DB.prepare('SELECT * FROM banners WHERE active=1 ORDER BY sort_order,id').all();return json({settings:Object.fromEntries(results.map(x=>[x.key,x.value])),banners})}
return json({error:'API not found'},404)}
if(u.pathname==='/admin'||u.pathname==='/admin/')return e.ASSETS.fetch(new Request(new URL('/admin.html',req.url),req));return e.ASSETS.fetch(req)}catch(err){return json({error:'خطای سرور',detail:err.message},500)}}};
